using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace ViverBem.Application.ViewModels
{
    public class ProfissaoViewModel
    {
        [Key]
        public int Id { get; set; }
        public string profcod { get; set; }
        public string profdesc { get; set; }

        public static List<ProfissaoViewModel> ListarProfissoes()
        {
            return new List<ProfissaoViewModel>()
            {
                new ProfissaoViewModel() {profcod="1", profdesc="SOLDADO"},
                new ProfissaoViewModel() {profcod="2", profdesc="CABO"},
                new ProfissaoViewModel() {profcod="3", profdesc="SARGENTO"},
                new ProfissaoViewModel() {profcod="4", profdesc="SUB TENENTE"},
                new ProfissaoViewModel() {profcod="5", profdesc="TENENTE"},
                new ProfissaoViewModel() {profcod="6", profdesc="CAPITAO"},
                new ProfissaoViewModel() {profcod="7", profdesc="MAJOR"},
                new ProfissaoViewModel() {profcod="8", profdesc="TENENTE CORONEL"},
                new ProfissaoViewModel() {profcod="9", profdesc="CORONEL"},
                new ProfissaoViewModel() {profcod="10", profdesc="FUNCIONARIO CIVIL"},
                new ProfissaoViewModel() {profcod="11", profdesc="COMISSARIO DE POLICIA"},
                new ProfissaoViewModel() {profcod="12", profdesc="OFICIAL DE CARTORIO"},
                new ProfissaoViewModel() {profcod="100", profdesc="GARI E ASSEMELHADOS"},
                new ProfissaoViewModel() {profcod="101", profdesc="ENGENHEIRO"},
                new ProfissaoViewModel() {profcod="102", profdesc="ARQUITETO"},
                new ProfissaoViewModel() {profcod="103", profdesc="AGRONOMO"},
                new ProfissaoViewModel() {profcod="104", profdesc="QUIMICO"},
                new ProfissaoViewModel() {profcod="105", profdesc="DESENHISTA INDUSTRIAL"},
                new ProfissaoViewModel() {profcod="106", profdesc="FISICO"},
                new ProfissaoViewModel() {profcod="107", profdesc="GEOLOGO"},
                new ProfissaoViewModel() {profcod="111", profdesc="MEDICO"},
                new ProfissaoViewModel() {profcod="112", profdesc="VETERINARIO E ZOOTECNISTA"},
                new ProfissaoViewModel() {profcod="113", profdesc="ENFERMEIRO E NUTRICIONISTA"},
                new ProfissaoViewModel() {profcod="114", profdesc="FISIOTERAPEUTA"},
                new ProfissaoViewModel() {profcod="115", profdesc="ODONTOLOGO"},
                new ProfissaoViewModel() {profcod="116", profdesc="BIOLOGO E BIOMEDICO"},
                new ProfissaoViewModel() {profcod="117", profdesc="FARMACEUTICO"},
                new ProfissaoViewModel() {profcod="118", profdesc="FONOAUDIOLOGO"},
                new ProfissaoViewModel() {profcod="121", profdesc="ECONOMISTA"},
                new ProfissaoViewModel() {profcod="122", profdesc="ESTATISTICO"},
                new ProfissaoViewModel() {profcod="123", profdesc="ATUARIO E MATEMATICO"},
                new ProfissaoViewModel() {profcod="124", profdesc="CONTADOR"},
                new ProfissaoViewModel() {profcod="125", profdesc="ADMINISTRADOR"},
                new ProfissaoViewModel() {profcod="126", profdesc="ANALISTA DE SISTEMAS"},
                new ProfissaoViewModel() {profcod="127", profdesc="GEOGRAFO"},
                new ProfissaoViewModel() {profcod="128", profdesc="ASTRONOMO E METEOROLOGISTA"},
                new ProfissaoViewModel() {profcod="131", profdesc="ADVOGADO"},
                new ProfissaoViewModel() {profcod="132", profdesc="PSICOLOGO"},
                new ProfissaoViewModel() {profcod="133", profdesc="SOCIOLOGO"},
                new ProfissaoViewModel() {profcod="134", profdesc="ASSISTENTE SOCIAL"},
                new ProfissaoViewModel() {profcod="135", profdesc="BIBLIOTECARIO"},
                new ProfissaoViewModel() {profcod="136", profdesc="COMUNICOLOGO"},
                new ProfissaoViewModel() {profcod="137", profdesc="RELACOES PUBLICAS"},
                new ProfissaoViewModel() {profcod="142", profdesc="PROFESSOR DE ENSINO SUPERIOR"},
                new ProfissaoViewModel() {profcod="143", profdesc="PROFESSOR DE 1 E 2 GRAUS"},
                new ProfissaoViewModel() {profcod="144", profdesc="DIR DE ESTABELECIMENTO ENSINO"},
                new ProfissaoViewModel() {profcod="151", profdesc="TECNICO DE CONTABILIDADE"},
                new ProfissaoViewModel() {profcod="152", profdesc="TECNICO DE BIOLOGIA"},
                new ProfissaoViewModel() {profcod="153", profdesc="TECNICO EM AGRONOMIA"},
                new ProfissaoViewModel() {profcod="154", profdesc="TECNICO DE QUIMICA"},
                new ProfissaoViewModel() {profcod="155", profdesc="TECNICO DE MECANICA"},
                new ProfissaoViewModel() {profcod="156", profdesc="TEC DE ELETRIC E ELETRONICA"},
                new ProfissaoViewModel() {profcod="157", profdesc="TEC DE LABORATORIO E RAIO X"},
                new ProfissaoViewModel() {profcod="158", profdesc="DESENHISTA TECNICO"},
                new ProfissaoViewModel() {profcod="161", profdesc="EMPRES E DIRETORDE ESPETACULOS"},
                new ProfissaoViewModel() {profcod="162", profdesc="ATOR E DIRETOR"},
                new ProfissaoViewModel() {profcod="163", profdesc="CANTOR E COMPOSITOR"},
                new ProfissaoViewModel() {profcod="164", profdesc="MUSICO"},
                new ProfissaoViewModel() {profcod="165", profdesc="COREOGRAFO E BAILARINO"},
                new ProfissaoViewModel() {profcod="166", profdesc="LOCUTOR COMENT E RADIALISTA"},
                new ProfissaoViewModel() {profcod="167", profdesc="OPERADOR DE CAMARA DE CINE TV"},
                new ProfissaoViewModel() {profcod="168", profdesc="ATLETA PROFE TECNICOEMDESPORTO"},
                new ProfissaoViewModel() {profcod="181", profdesc="PILOTO DE AERONAVES"},
                new ProfissaoViewModel() {profcod="182", profdesc="COMISSARIO DE BORDO"},
                new ProfissaoViewModel() {profcod="183", profdesc="COMANDANTE DE EMBARCACOES"},
                new ProfissaoViewModel() {profcod="191", profdesc="ESCULTOR PINTOR ARTISTICO"},
                new ProfissaoViewModel() {profcod="192", profdesc="DESENHISTA COMERCIAL"},
                new ProfissaoViewModel() {profcod="193", profdesc="DECORADOR"},
                new ProfissaoViewModel() {profcod="205", profdesc="DESEMBARGADOR E JUIZ"},
                new ProfissaoViewModel() {profcod="211", profdesc="PROCURADOR"},
                new ProfissaoViewModel() {profcod="212", profdesc="DIPLOMATA"},
                new ProfissaoViewModel() {profcod="213", profdesc="FISCAL"},
                new ProfissaoViewModel() {profcod="214", profdesc="DELEGADO DE POLICIA"},
                new ProfissaoViewModel() {profcod="215", profdesc="OCUPANTE DE CARGO DE DIRECAO"},
                new ProfissaoViewModel() {profcod="216", profdesc="OFICI DAS FORCAS ARM E MILITAR"},
                new ProfissaoViewModel() {profcod="217", profdesc="PRACAS DAS POLICIAS MILITARES"},
                new ProfissaoViewModel() {profcod="291", profdesc="OCUPDE CAR DE DIR ASSIS INTERM"},
                new ProfissaoViewModel() {profcod="292", profdesc="AGENTE ADMINISTRATIVO"},
                new ProfissaoViewModel() {profcod="293", profdesc="SERVENTUARIO DA JUSTICA"},
                new ProfissaoViewModel() {profcod="294", profdesc="TABELIAO"},
                new ProfissaoViewModel() {profcod="295", profdesc="MILITAR PRACAS DAS FORCAS ARMADAS"},
                new ProfissaoViewModel() {profcod="296", profdesc="SER PUBLIC CIVIL FEDERAL"},
                new ProfissaoViewModel() {profcod="297", profdesc="SERV PUBLIC CIVIL ESTADUAL"},
                new ProfissaoViewModel() {profcod="298", profdesc="SERV PUBLIC CIVIL MUNICIPAL"},
                new ProfissaoViewModel() {profcod="301", profdesc="DIRETOR DE EMPRESA"},
                new ProfissaoViewModel() {profcod="303", profdesc="GERENTE"},
                new ProfissaoViewModel() {profcod="304", profdesc="AMBULANTE E CAMELO"},
                new ProfissaoViewModel() {profcod="305", profdesc="ANTROPOLOGO E ARQUEOLOGO"},
                new ProfissaoViewModel() {profcod="306", profdesc="ARQUIVOLOGISTA E MUSEOLOGO"},
                new ProfissaoViewModel() {profcod="307", profdesc="AUDITOR"},
                new ProfissaoViewModel() {profcod="308", profdesc="BOMBEIRO MILITAR"},
                new ProfissaoViewModel() {profcod="309", profdesc="CENOGRAFO"},
                new ProfissaoViewModel() {profcod="310", profdesc="CIENTISTA"},
                new ProfissaoViewModel() {profcod="311", profdesc="CINEGRAFISTA"},
                new ProfissaoViewModel() {profcod="312", profdesc="COMANDANTE DE AERONAVE"},
                new ProfissaoViewModel() {profcod="313", profdesc="CONSULTOR"},
                new ProfissaoViewModel() {profcod="314", profdesc="DO LAR"},
                new ProfissaoViewModel() {profcod="315", profdesc="ESCRITOR E REDATOR"},
                new ProfissaoViewModel() {profcod="316", profdesc="FILOSOFO"},
                new ProfissaoViewModel() {profcod="317", profdesc="FOTOGRAFO"},
                new ProfissaoViewModel() {profcod="318", profdesc="HISTORIADOR"},
                new ProfissaoViewModel() {profcod="319", profdesc="INTERPRETE"},
                new ProfissaoViewModel() {profcod="320", profdesc="JOALHEIRO"},
                new ProfissaoViewModel() {profcod="321", profdesc="JORNALISTA E REPORTER"},
                new ProfissaoViewModel() {profcod="322", profdesc="METEOROLOGISTA"},
                new ProfissaoViewModel() {profcod="323", profdesc="MILITAR DA AERONAUTICA"},
                new ProfissaoViewModel() {profcod="324", profdesc="MILITAR DA MARINHA"},
                new ProfissaoViewModel() {profcod="325", profdesc="MILITAR DO EXERCITO"},
                new ProfissaoViewModel() {profcod="326", profdesc="OFICIAL DE JUSTICA"},
                new ProfissaoViewModel() {profcod="327", profdesc="OPERADOR DE MAQUINA"},
                new ProfissaoViewModel() {profcod="328", profdesc="PERSONAL TRAINER"},
                new ProfissaoViewModel() {profcod="329", profdesc="TRABALHADOR AGRICOLA, PECUARIA E PESCA"},
                new ProfissaoViewModel() {profcod="330", profdesc="POLICIAL MILITAR"},
                new ProfissaoViewModel() {profcod="331", profdesc="PRESIDENTE"},
                new ProfissaoViewModel() {profcod="332", profdesc="PRODUTOR DE ESPETACULOS"},
                new ProfissaoViewModel() {profcod="333", profdesc="PROFISSIONAL DE MARKETING"},
                new ProfissaoViewModel() {profcod="334", profdesc="PROMOTOR"},
                new ProfissaoViewModel() {profcod="335", profdesc="PSICANALISTA"},
                new ProfissaoViewModel() {profcod="336", profdesc="PUBLICITARIO"},
                new ProfissaoViewModel() {profcod="337", profdesc="SACERDOTE OU RELIGIOSO"},
                new ProfissaoViewModel() {profcod="338", profdesc="SINDICALISTA"},
                new ProfissaoViewModel() {profcod="339", profdesc="TITULAR DE CARTORIO"},
                new ProfissaoViewModel() {profcod="340", profdesc="TRADUTOR"},
                new ProfissaoViewModel() {profcod="341", profdesc="TRAINEE"},
                new ProfissaoViewModel() {profcod="342", profdesc="VITRINISTA"},
                new ProfissaoViewModel() {profcod="343", profdesc="ESTUDANTE"},
                new ProfissaoViewModel() {profcod="344", profdesc="OUTROS"},
                new ProfissaoViewModel() {profcod="377", profdesc="AVIADOR AGRICOLA E LINHA N REG"},
                new ProfissaoViewModel() {profcod="391", profdesc="CHEFE INTERMEDIARIO"},
                new ProfissaoViewModel() {profcod="392", profdesc="SERVICOS DE CAIXACONTABILIDADE"},
                new ProfissaoViewModel() {profcod="393", profdesc="SECRETDATILOG RECEP TELEFONIST"},
                new ProfissaoViewModel() {profcod="394", profdesc="AUXILIAR DE ESCRITORIO"},
                new ProfissaoViewModel() {profcod="395", profdesc="BANCARIO E ECONOMISTA"},
                new ProfissaoViewModel() {profcod="396", profdesc="SECURITARIO"},
                new ProfissaoViewModel() {profcod="401", profdesc="SUPERV INSPETOR E AGENTE"},
                new ProfissaoViewModel() {profcod="402", profdesc="VENDEDOR REPRESENCOMERCIAL"},
                new ProfissaoViewModel() {profcod="403", profdesc="CORRETOR EM GERAL"},
                new ProfissaoViewModel() {profcod="404", profdesc="LEILOEIRO AVALIADOR"},
                new ProfissaoViewModel() {profcod="405", profdesc="AGENCIADOR DE PROPAGANDA"},
                new ProfissaoViewModel() {profcod="411", profdesc="VENDEDOR DO COMERCIO"},
                new ProfissaoViewModel() {profcod="412", profdesc="JORNALEIRO"},
                new ProfissaoViewModel() {profcod="413", profdesc="FEIRANTE"},
                new ProfissaoViewModel() {profcod="491", profdesc="DEMONSTRADOR"},
                new ProfissaoViewModel() {profcod="492", profdesc="MODELO DE MODAS"},
                new ProfissaoViewModel() {profcod="501", profdesc="PORTEIRO ASCENSORISTAFAXINEIRO"},
                new ProfissaoViewModel() {profcod="511", profdesc="TAXISTA,COBRADOR DE ONIBUS"},
                new ProfissaoViewModel() {profcod="514", profdesc="LIMPADOR DE VIDROS EM EDIFICIO"},
                new ProfissaoViewModel() {profcod="516", profdesc="CABELEIREIRO"},
                new ProfissaoViewModel() {profcod="521", profdesc="GOVERNANTA CAMAREIRO GARCON"},
                new ProfissaoViewModel() {profcod="530", profdesc="MOTORISTA"},
                new ProfissaoViewModel() {profcod="541", profdesc="MECANICO E SOLDADOR"},
                new ProfissaoViewModel() {profcod="542", profdesc="ELETRICISTA, ENCADOR E PINTOR"},
                new ProfissaoViewModel() {profcod="543=", profdesc="MECANICO,SOLDADOR E LANTERNEIRO(A)"},
                new ProfissaoViewModel() {profcod="544", profdesc="BOMBEIRO E INST DE GAS AGUA"},
                new ProfissaoViewModel() {profcod="591", profdesc="ALFAIATE"},
                new ProfissaoViewModel() {profcod="592", profdesc="PROTETICO"},
                new ProfissaoViewModel() {profcod="593", profdesc="DESPACHANTE"},
                new ProfissaoViewModel() {profcod="594", profdesc="AGENTE DE VIAGEM TURISMO"},
                new ProfissaoViewModel() {profcod="595", profdesc="AGENTE FUNERARIO EMBALSAMADOR"},
                new ProfissaoViewModel() {profcod="596", profdesc="AUXILIAR DE LABORATORIO"},
                new ProfissaoViewModel() {profcod="597", profdesc="ESTIVADOR CARREDOR"},
                new ProfissaoViewModel() {profcod="598", profdesc="EMPREGADO DOMESTICO"},
                new ProfissaoViewModel() {profcod="599", profdesc="SERV PUBLICO CIVIL DA BM"},
                new ProfissaoViewModel() {profcod="632", profdesc="TRAB COM UTI AGROTOXICO PESTIC"},
                new ProfissaoViewModel() {profcod="700", profdesc="TRABALHADOR INDUSTRIAL"},
                new ProfissaoViewModel() {profcod="711", profdesc="MINEIRO,GARIMPEIRO E ASSEMELHA"},
                new ProfissaoViewModel() {profcod="731", profdesc="INSTALADOR(GAS,AGUA,ESGOTO ETC)"},
                new ProfissaoViewModel() {profcod="771", profdesc="MARCENEIRO E SERRALHEIRO"},
                new ProfissaoViewModel() {profcod="781", profdesc="MERGULHADOR"},
                new ProfissaoViewModel() {profcod="782", profdesc="MOTORISTA DE ONIBUS E CAMINHOES"},
                new ProfissaoViewModel() {profcod="811", profdesc="TRAB IND SOLVENTES TINTAS E CO"},
                new ProfissaoViewModel() {profcod="812", profdesc="VERRUMEIRO (TRAB EXPLOSIVOS)"},
                new ProfissaoViewModel() {profcod="813", profdesc="TRAB IND PETROQ, FRENTISTA E G"},
                new ProfissaoViewModel() {profcod="842", profdesc="FABRICACAO DE FUMO/FUMAGEIROS"},
                new ProfissaoViewModel() {profcod="848", profdesc="ACOUGUEIRO, AFIADORES E ASSEME"},
                new ProfissaoViewModel() {profcod="902", profdesc="PROPRIETARIO DE EST COMERCIAL"},
                new ProfissaoViewModel() {profcod="903", profdesc="PROPRIETARIO DE EST INDUSTRIAL"},
                new ProfissaoViewModel() {profcod="904", profdesc="PROPRIETARIO DE EST PRESTACAO SERV"},
                new ProfissaoViewModel() {profcod="905", profdesc="PROPRIETARIO DE MICROEMPRESA"},
                new ProfissaoViewModel() {profcod="906", profdesc="PROPRIETARIO DE IMOVEL"},
                new ProfissaoViewModel() {profcod="921", profdesc="MILITAR REFORMADO OFICIAIS"},
                new ProfissaoViewModel() {profcod="922", profdesc="FUNCIONARIO PUBLICO CIVIL APOSENTADO"},
                new ProfissaoViewModel() {profcod="923", profdesc="APOSENTADOS EXCETO FUNC PUBLIC"},
                new ProfissaoViewModel() {profcod="924", profdesc="PENSIONISTA"},
                new ProfissaoViewModel() {profcod="993", profdesc="EXTRACAO REFINACAO DE PETROLEO"},
                new ProfissaoViewModel() {profcod="996", profdesc="MOTOBOY E ASSEMELHADOS"},
                new ProfissaoViewModel() {profcod="997", profdesc="APOSENTADO POR IDADE"},
                new ProfissaoViewModel() {profcod="998", profdesc="APOSENTADO POR TEMPO DE SERVIC"},
                new ProfissaoViewModel() {profcod="999", profdesc="APOSENTADO POR INVALIDEZ"}
            };
        }
    }
}
